/** Leads formatados (parágrafos + termos SEO em <strong>) por marca. Reformatação fiel do `resumo` de cada marca em marcas.ts — sem alterar o conteúdo. */
export const MARCAS_LEADS: Record<string, string> = {
  chevrolet: `<p>A <strong>Chevrolet</strong> está presente em praticamente todo estacionamento brasileiro, e os motivos ficam claros olhando para o portfólio. O <strong>Onix</strong> hatch e o <strong>Onix Plus</strong> sedã dominaram o segmento de entrada por anos, enquanto o <strong>Tracker</strong> turbinado conquistou o mercado de SUVs compactos. A <strong>S10</strong> figura entre as picapes mais procuradas para uso misto, e a <strong>Spin</strong> segue como referência em monovolumes de sete lugares.</p>
<p>Motoricamente, a linha atual aposta no <strong>1.0 turbo Flex</strong> de três cilindros, um motor ágil que exige troca de óleo rigorosa porque o turbo opera em rotações altas mesmo em uso urbano.</p>
<p>O câmbio automático de seis marchas do Tracker convive bem com o dia a dia, porém o <strong>CVT</strong> da geração anterior do Onix Plus merece inspeção preventiva do fluido a cada 40 mil km.</p>
<p>O mecânico deve ficar de olho no nível de refrigerante, pois o motor 1.0 turbo aquece mais rápido em trânsito lento, e na <strong>corrente de distribuição</strong> nos exemplares mais antigos do <strong>1.4 EcoTec</strong>, que apresentou desgaste prematuro quando o óleo esteve fora do prazo de troca.</p>`,
  fiat: `<p>A <strong>Fiat</strong> é a fabricante com maior presença nas estradas brasileiras, e os números comprovam essa liderança. A <strong>Strada</strong> domina o segmento de picapes compactas com folga, o <strong>Argo</strong> dividiu o mercado de hatches populares com o <strong>Mobi</strong> de entrada, e o <strong>Toro</strong> consolidou a marca no segmento de picapes médias. O <strong>Pulse</strong> SUV e o <strong>Cronos</strong> sedã completam o portfólio atual, ambos com o motor <strong>Firefly 1.3 turbo</strong> como topo de gama a combustão.</p>
<p>O Firefly em versão aspirada é simples e econômico, mas exige atenção ao ajuste de válvulas a cada 30 mil km, um intervalo mais curto do que o habitual para a categoria. O motor <strong>E.torQ 1.8</strong>, ainda presente em versões mais antigas do Argo e da Toro, tem boa durabilidade, porém apresentou problemas com velas de ignição se não forem trocadas na manutenção prevista.</p>
<p>O <strong>câmbio CVT</strong> do Pulse foi alvo de recall em alguns lotes, e o mecânico deve conferir o histórico do veículo antes de qualquer revisão. Para as picapes, inspecionar o diferencial traseiro da Toro 4x4 a cada revisão é prática que evita reparos de alto custo no futuro.</p>`,
  hyundai: `<p>A <strong>Hyundai</strong> chegou ao Brasil com o <strong>HB20</strong> e rapidamente emplacou o modelo como favorito no segmento de entrada. Hoje, o HB20 hatch e o <strong>HB20S</strong> sedã mantêm boa demanda, mas é o <strong>Creta</strong> que sustenta os números maiores de emplacamento, especialmente nas versões Limited com motor 2.0 aspirado e câmbio automático de seis marchas. O <strong>Tucson</strong> e o <strong>Santa Fe</strong> atendem o público que busca mais espaço e acabamento premium.</p>
<p>Tecnicamente, o <strong>motor 1.0 turbo</strong> do HB20 é compacto e eficiente, porém demanda troca de óleo a cada 10 mil km no máximo por conta do turbo de geometria fixa. O <strong>câmbio CVT</strong> com correia metálica da geração anterior do HB20 merece atenção: se o fluido não foi trocado dentro do prazo, há risco de deslizamento e perda de eficiência.</p>
<p>O mecânico deve verificar o estado do filtro de ar e do <strong>sensor de fluxo de massa</strong> nos motores 1.6 aspirado, pois esse sensor, quando sujo, gera falhas de mistura que imitam problema no catalisador. A vida útil das pastilhas de freio dianteiras no Creta 2.0 costuma ser mais curta do que o previsto por proprietários que fazem trajetos com muitas descidas ou frenagens frequentes.</p>`,
  ford: `<p>A <strong>Ford</strong> encerrou a produção no Brasil em 2021, mas <strong>Ka</strong>, <strong>EcoSport</strong>, <strong>Fusion</strong> e <strong>Ranger</strong> ainda circulam em grande número pelo país. O Ka foi fenômeno de vendas com motor <strong>Dragon 1.5</strong> e <strong>1.0 EcoBoost</strong>, enquanto o EcoSport, pioneiro do segmento SUV compacto nacional, ainda mantém valores razoáveis de revenda. A Ranger segue sendo oferecida no Brasil como produto importado e continua entre as picapes mais admiradas do segmento.</p>
<p>O motor EcoBoost 1.0 do Ka tem fama de consumo eficiente, mas exige atenção ao sistema de arrefecimento: a sonda lambda e o sensor de temperatura tendem a acusar falha quando o líquido de arrefecimento está abaixo do nível.</p>
<p>O <strong>câmbio PowerShift</strong> de dupla embreagem seca, presente nos Ka e <strong>Focus</strong> de período mais antigo, foi o ponto mais crítico da linha: ruídos ao engatar primeira marcha e solavancos em fila são sintomas que exigem atualização de software ou substituição do kit de embreagem.</p>
<p>O mecânico que receber um Ford desse período deve verificar o histórico de recalls antes de qualquer diagnóstico, pois a montadora emitiu vários boletins de serviço e as peças ainda têm disponibilidade razoável nas redes autorizadas mesmo após a saída do mercado.</p>`,
  jeep: `<p>A <strong>Jeep</strong> reinventou o gosto brasileiro por SUVs quando lançou o <strong>Renegade</strong> em 2015, e desde então não saiu do radar dos consumidores. O <strong>Compass</strong> tomou conta do segmento intermediário com acabamento premium, e o <strong>Commander</strong> chegou para atender famílias que precisam de sete lugares com tração. Todos os modelos mais recentes são movidos pelo motor <strong>1.3 turbo T270</strong> ou T4, desenvolvido em parceria com a Stellantis, com potência entre 150 e 185 cv dependendo da versão.</p>
<p>O ponto de atenção mais citado em oficinas é o sistema de arrefecimento: o T270 opera próximo da temperatura máxima em uso urbano intenso, e qualquer vazamento por mangueiras ou tampa do radiador pode levar ao <strong>superaquecimento</strong> rapidamente.</p>
<p>O câmbio automático de nove marchas do Compass T4 é suave, mas deve ter o fluido trocado a cada 60 mil km, pois muitos proprietários ignoram esse item e enfrentam solavancos precoces.</p>
<p>No Commander, o mecânico deve inspecionar as buchas do braço de controle dianteiro nas revisões, pois a <strong>suspensão multilink</strong> sofre mais com a carga de sete ocupantes em ruas esburacadas. Peças originais têm boa distribuição no Brasil por meio da rede Stellantis.</p>`,
  renault: `<p>A <strong>Renault</strong> é uma das marcas que melhor soube adaptar seus modelos ao gosto e ao bolso brasileiro. O <strong>Kwid</strong> abriu o segmento de SUV de entrada com preço de popular, o <strong>Sandero</strong> mantém fidelidade entre quem prefere câmbio manual, e o <strong>Duster</strong> ainda é referência em custo-benefício nos SUVs compactos. O <strong>Captur</strong> e o <strong>Oroch</strong>, derivado do Duster com caçamba, completam o portfólio atual.</p>
<p>O <strong>motor 1.6 aspirado SCe</strong> presente em várias versões é simples, robusto e de manutenção barata, o que explica o alto índice de satisfação em pesquisas de custo operacional. O <strong>câmbio CVT X-Tronic</strong> do Captur e do Duster 2.0 tem desempenho adequado para o uso urbano, mas o fluido deve ser trocado a cada 40 mil km: sem essa troca, o sistema de correia interna desgasta antes do esperado.</p>
<p>O mecânico deve observar o estado dos coxins do motor no Duster 2.0, que vibra mais em marcha lenta quando os suportes estão desgastados, e verificar o sensor de posição do acelerador no Kwid, cujo pedal eletrônico é mais sensível à sujeira do que nos concorrentes japoneses. A rede de peças da Renault no Brasil é abrangente e com preços competitivos.</p>`,
  toyota: `<p>A <strong>Toyota</strong> construiu no Brasil uma reputação de durabilidade que poucos fabricantes conseguem igualar. O <strong>Corolla</strong> sedã permanece como referência de confiabilidade entre sedãs médios, e o <strong>Corolla Cross</strong> trouxe o visual de SUV sem abrir mão da mecânica híbrida disponível na versão topo. A <strong>Hilux</strong> é a picape mais valorizada na revenda e a mais escolhida por quem trabalha em zonas rurais. O <strong>Yaris</strong> hatch e sedã atendem o público que quer um Toyota de entrada sem abrir mão da extensa rede autorizada.</p>
<p>Os motores <strong>2.0 flex Dynamic Force</strong> e o sistema híbrido 1.8 do Corolla Cross são de alta durabilidade, mas o mecânico deve checar o estado dos injetores nos motores de <strong>injeção direta</strong> a cada 60 mil km para evitar acúmulo de carbono nas válvulas. Na Hilux, o ponto mais sensível é a bomba de combustível do <strong>diesel 2.8 Turbo</strong>, com relatos de entupimento em postos com combustível de baixa qualidade.</p>
<p>O câmbio automático de seis marchas presente nos modelos flex é bastante robusto, mas o <strong>fluido ATF</strong> deve ser trocado a cada 80 mil km para preservar a suavidade das trocas. A rede de peças da Toyota é das mais organizadas e ágeis do Brasil.</p>`,
  nissan: `<p>A <strong>Nissan</strong> se firmou no Brasil principalmente por dois modelos de volume: o <strong>Kicks</strong> SUV compacto e o <strong>Versa</strong> sedã. O Kicks conquistou o mercado com design arrojado e <strong>câmbio CVT Xtronic</strong> bem calibrado, enquanto o Versa se manteve como opção econômica e espaçosa para quem não abre mão de um porta-malas generoso. A <strong>Frontier</strong> diesel continua sendo a picape de trabalho pesado preferida por fazendeiros e construtores que não querem pagar o preço premium de uma Hilux.</p>
<p>O câmbio CVT Xtronic usa uma polia de variação contínua que depende de fluido limpo para funcionar bem: a Nissan recomenda troca a cada 30 mil km, mas boa parte dos proprietários ultrapassa esse intervalo. O mecânico deve testar o comportamento do câmbio em frenagem suave, pois qualquer solavanquinho ou demora para retomar a tração indica desgaste inicial da correia interna.</p>
<p>Na <strong>Frontier 2.3 biturbo</strong>, a <strong>corrente de distribuição</strong> pode apresentar ruído ao arrancar a frio se o óleo estiver degradado, e usar viscosidade 5W-30 sintético é a recomendação mais segura para preservar a cadeia. O estoque de peças da Nissan no Brasil é razoável, com prazos de entrega um pouco maiores do que os das marcas japonesas com produção local.</p>`,
  honda: `<p>A <strong>Honda</strong> tem no Brasil um portfólio enxuto e bem focado: <strong>City</strong> sedã e hatch, <strong>HR-V</strong> SUV compacto, <strong>WR-V</strong> e o <strong>Civic</strong> nas versões 1.5 turbo. O City é, possivelmente, o sedã mais recomendado por mecânicos independentes no segmento compacto, com motor 1.5 Flex aspirado simples, durável e peças de preço acessível. O HR-V 1.5 turbo da segunda geração subiu de patamar em refinamento, mas trouxe a complexidade de um <strong>motor turbo de três cilindros</strong> que exige mais atenção nas revisões.</p>
<p>O <strong>câmbio CVT</strong> presente em toda a linha atual é suave e bem calibrado, porém o fluido precisa ser trocado antes dos 40 mil km para evitar solavancos à baixa velocidade. O ponto mais crítico na atual geração do HR-V é o <strong>sensor de velocidade de roda traseira</strong>, que pode gerar falsa ativação do controle de estabilidade em pavimento irregular, problema com solução via atualização de software na rede autorizada.</p>
<p>No City 1.5 flex, o mecânico deve verificar o estado das buchas do braço de controle traseiro após 60 mil km: peças originais têm preço acessível e a substituição preventiva evita que o pneu traseiro desgaste irregularmente antes do prazo. A rede Honda tem cobertura abrangente nas capitais e no interior.</p>`,
  byd: `<p>A <strong>BYD</strong> chegou ao Brasil como a montadora elétrica que levou o segmento a sério, e os emplacamentos confirmaram que o mercado respondeu. O <strong>Dolphin</strong> compacto tornou o elétrico acessível para o público urbano, enquanto o <strong>Song Plus</strong> híbrido plug-in (PHEV) abriu o segmento para quem ainda hesita com a autonomia elétrica pura. O <strong>Seal</strong> sedã e o <strong>Atto 3</strong> SUV completam a gama, com o <strong>Tan</strong> e o <strong>King</strong> atendendo o topo da linha.</p>
<p>A tecnologia <strong>Blade Battery</strong>, com células LFP integradas ao assoalho, é o principal diferencial técnico: maior resistência a impactos e menor risco de ignição em acidentes comparado às baterias NMC convencionais. O mecânico independente que quiser atender esses modelos precisa de equipamento de isolamento de alta tensão (mínimo 1000 V) e certificação específica, pois sistemas de 400 V exigem precauções bem além do treinamento convencional.</p>
<p>O ponto prático mais importante na revisão é o <strong>gerenciamento térmico da bateria</strong>: verificar o fluido refrigerante do circuito elétrico, separado do circuito do motor, dentro do nível e no prazo é tão crítico quanto checar o fluido de freio. A rede autorizada BYD cresceu rápido no Brasil, com cobertura boa nas capitais e expansão contínua para o interior.</p>`,
  peugeot: `<p>A <strong>Peugeot</strong> voltou a aparecer com frequência nas pesquisas de consumidores brasileiros após o lançamento do <strong>208</strong> hatch e do <strong>2008</strong> SUV, ambos com design europeu moderno e bom nível de acabamento. O <strong>3008</strong> e o <strong>408</strong> completam a gama para quem busca mais espaço ou um perfil de crossover alongado.</p>
<p>Os motores da família <strong>PureTech</strong>, especialmente o 1.2 turbo de três cilindros que substituiu o <strong>1.6 THP</strong>, têm eficiência energética excelente. O 1.6 THP ainda presente em alguns seminovos é conhecido pelo <strong>acúmulo de carbono nas válvulas de admissão</strong>: uma limpeza por injeção a cada 30-40 mil km prolonga muito a vida útil sem custos altos.</p>
<p>O <strong>câmbio automático EAT8</strong> de oito marchas é refinado e rápido nas trocas, porém exige troca de fluido a cada 60 mil km, pois deixar passar esse prazo é a principal causa de solavancos notados em baixa velocidade.</p>
<p>O mecânico deve prestar atenção no <strong>sensor de pressão de óleo</strong> do motor PureTech 1.2, que tem relatos de falha prematura acendendo o alarme de óleo sem queda real de pressão: o diagnóstico correto por leitor OBD evita reparos desnecessários e economiza o bolso do proprietário.</p>`,
  citroen: `<p>A <strong>Citroën</strong> conquistou um nicho fiel no Brasil apostando em conforto de suspensão e design diferenciado. O <strong>C3</strong> popular virou um best-seller inesperado ao oferecer <strong>câmbio automatizado (AMT)</strong>, ar-condicionado e direção elétrica a um preço competitivo. O <strong>C4 Cactus</strong> e o <strong>C5 Aircross</strong> atendem quem quer mais refinamento, com suspensão de amortecedores hidráulicos progressivos no C5 para melhorar o conforto em estradas ruins.</p>
<p>Os motores usados são o 1.0 e <strong>1.2 turbo PureTech</strong> compartilhados com a Peugeot, além do <strong>1.6 THP</strong> em versões mais antigas. O câmbio automatizado de dois pedais do C3 de entrada funciona bem em uso tranquilo, mas os solavancos em tráfego congestionado são inerentes ao sistema AMT e o mecânico não deve confundir esse comportamento normal com defeito mecânico.</p>
<p>No C5 Aircross, a suspensão progressive hydraulic cushions tem durabilidade alta, porém quando as hastes do amortecedor apresentam corrosão o custo de substituição é elevado. O filtro de ar e o filtro de combustível do 1.2 turbo devem ser trocados rigorosamente no prazo, pois o turbo de pequeno volume é sensível a variações na qualidade do ar e do combustível, cuidado básico que evita gastos maiores na bomba de combustível e no próprio turbo.</p>`,
  mitsubishi: `<p>A <strong>Mitsubishi</strong> ocupa no Brasil um espaço particular: não compete no volume dos populares, mas construiu uma base leal de clientes que valoriza robustez e tração 4x4. O <strong>L200 Triton Sport</strong> é a picape de trabalho preferida por fazendeiros e aventureiros que precisam de carga pesada e terreno difícil. O <strong>Eclipse Cross</strong> e o <strong>Outlander</strong> atendem o público de SUVs médios, enquanto o <strong>ASX</strong> tem presença mais tímida no mercado nacional.</p>
<p>O <strong>motor 2.4 MIVEC flex</strong> aspirado tem reputação de durabilidade, mas o ajuste de folga de válvulas deve ser verificado após o primeiro aquecimento em motores que ficaram parados por longo período. No L200 Triton, o motor <strong>2.4 turbo diesel di-D</strong> tem injetores sensíveis à qualidade do combustível: usar diesel de posto confiável e trocar o filtro dentro do prazo reduz o risco de entupimento da bomba injetora, reparo que pode custar caro.</p>
<p>O <strong>câmbio CVT</strong> do Eclipse Cross exige troca de fluido a cada 40 mil km, intervalo que muitos proprietários ignoram por não haver sinalização no painel. O diferencial traseiro da Triton 4x4 deve ser inspecionado a cada 40 mil km ou após uso intenso em lama, com troca de óleo para evitar desgaste precoce das engrenagens.</p>`,
  gwm: `<p>A <strong>GWM</strong> (Great Wall Motors) representa a nova onda de montadoras chinesas que chegaram ao Brasil com produtos de alto nível de especificação a preços competitivos. O <strong>Haval H6</strong> SUV médio foi o carro de estreia e ainda é o modelo mais vendido da marca no país, com motor 1.5 turbo e <strong>câmbio de dupla embreagem (DCT)</strong> de sete marchas. O <strong>Tank 300</strong> abriu o nicho de SUVs off-road premium, e o <strong>Ora 03</strong> elétrico entrou no segmento de EVs compactos.</p>
<p>O câmbio DCT dos modelos Haval passa por um período de adaptação nos primeiros 5 mil km, e solavancos leves ao arrancar são normais nessa fase: se persistirem além desse período, o mecânico deve verificar se há atualização de software disponível para o módulo de controle da transmissão.</p>
<p>O <strong>motor 1.5 turbo</strong> é econômico e responsivo, porém demanda óleo sintético 5W-40 ou 5W-30: usar lubrificante mineral ou semissintético acelera o desgaste do turbo. A rede de concessionários GWM cresceu rapidamente no Brasil, mas para cidades do interior a disponibilidade de peças de funilaria e vidros especiais merece verificação antes de fechar o negócio, pois os prazos de importação podem ser longos.</p>`,
  ram: `<p>A <strong>RAM</strong> é a marca de picapes da Stellantis com dois posicionamentos bem distintos no Brasil. O <strong>Rampage</strong> chegou como picape média acessível com motor <strong>2.0 turbo diesel</strong> de 170 cv e câmbio automático de nove marchas, combinação que entrega torque abundante para carga e reboque sem consumo excessivo. Já a <strong>RAM 1500</strong> <strong>V8 Hemi</strong> é a picape de luxo sem disfarce, com 5.7 litros, 395 cv e transmissão ZF de oito marchas para quem quer conforto de sedã com a capacidade de carga de uma fazenda.</p>
<p>O ponto mais crítico no Rampage diesel é a <strong>válvula EGR</strong> (recirculação de gases de escapamento): entupimento é queixa frequente em veículos urbanos que fazem trajetos curtos sem aquecimento completo do motor. Uma limpeza preventiva do EGR a cada 40-50 mil km evita queda de potência e eventual falha no teste de emissões.</p>
<p>Na RAM 1500, o fluido 5W-20 Mopar deve ser o especificado para o V8: substitutos de baixa qualidade podem gerar alerta de pressão de óleo no painel e acelerar o desgaste das bronzinas. A rede de garantia da RAM no Brasil cobre bem as capitais e tem expandido para as principais cidades do interior.</p>`,
  suzuki: `<p>A <strong>Suzuki</strong> ocupa um nicho muito específico no mercado brasileiro, e o <strong>Jimny</strong> é o coração desse nicho. O pequeno off-road com chassi de escada separado, caixa de redução e diferencial traseiro bloqueável é único entre os lançamentos da última década, e chegou ao mercado esgotando estoques com meses de antecedência em cada lote disponível. O <strong>Grand Vitara</strong> retornou ao portfólio para quem quer mais espaço sem abrir mão do 4x4 integral, e o <strong>Swift</strong> hatch entrou discretamente no segmento urbano.</p>
<p>O <strong>motor 1.5 K15B</strong> do Jimny tem consumo modesto para um off-road, mas o mecânico deve verificar o nível de óleo a cada 5 mil km, pois o propulsor consome uma pequena quantidade de lubrificante em uso fora de estrada intenso. A <strong>caixa de transferência AllGrip Pro</strong> merece inspeção do óleo a cada 40 mil km ou após uso pesado em lama.</p>
<p>Os freios do Jimny, dimensionados para o peso original do veículo, desgastam as pastilhas com mais rapidez em uso urbano frequente com carga e passageiros. Peças originais Suzuki têm disponibilidade razoável nas capitais, mas no interior o prazo de entrega pode ser longo, o que exige planejamento na manutenção preventiva.</p>`,
  'caoa-chery': `<p>A <strong>CAOA Chery</strong> reposicionou as marcas chinesas no Brasil ao entregar SUVs com acabamento competitivo e preço abaixo dos equivalentes europeus. O <strong>Tiggo 5X</strong> foi o modelo de estreia do novo posicionamento, seguido pelo <strong>Tiggo 7 Pro</strong> e o <strong>Tiggo 8 Pro</strong>, este último com motor 2.0 turbo de 197 cv e <strong>câmbio DCT</strong> de sete marchas. O Tiggo 5X usa o propulsor 1.5 turbo associado ao câmbio CVT ou DCT conforme a versão, sendo o mais indicado para uso urbano por conta do consumo mais contido.</p>
<p>O câmbio DCT dos modelos mais potentes exige um período de adaptação nos primeiros quilômetros, e solavancos ao sair do semáforo são normais nessa fase inicial. O mecânico deve acompanhar o calendário de troca do fluido do DCT com atenção: o intervalo recomendado é de 40 mil km, menor do que proprietários acostumados a marcas japonesas costumam esperar.</p>
<p>A <strong>correia dentada</strong> do motor 1.5 turbo tem intervalo de substituição mais curto do que o habitual em outros fabricantes, e ignorar essa troca pode resultar em falha catastrófica com encontro entre válvulas e pistões. A rede CAOA Chery tem boa cobertura nas capitais e está expandindo para cidades médias do interior.</p>`,
};
